# Create sample payload files

# Create test.php payload
php_payload = '''<?php
/*
 * Migr8 Test PHP Payload
 * Harmless reconnaissance payload for upload testing
 */

echo "<!-- Migr8 PHP Test Payload -->\\n";
echo "<h2>PHP Upload Test Successful</h2>\\n";
echo "<p>Server: " . $_SERVER['SERVER_SOFTWARE'] . "</p>\\n";
echo "<p>PHP Version: " . phpversion() . "</p>\\n";
echo "<p>Current Time: " . date('Y-m-d H:i:s') . "</p>\\n";
echo "<p>Upload Directory: " . __DIR__ . "</p>\\n";
echo "<p>File: " . __FILE__ . "</p>\\n";

// Basic system info (non-harmful)
if (function_exists('php_uname')) {
    echo "<p>System: " . php_uname() . "</p>\\n";
}

// Check if dangerous functions are disabled
$dangerous_functions = ['exec', 'shell_exec', 'system', 'passthru'];
foreach ($dangerous_functions as $func) {
    $status = function_exists($func) ? 'Available' : 'Disabled';
    echo "<p>Function $func: $status</p>\\n";
}

echo "<!-- End Migr8 PHP Test Payload -->\\n";
?>
'''

with open("migr8/payloads/test.php", 'w') as f:
    f.write(php_payload)
print("Created: migr8/payloads/test.php")

# Create test.aspx payload  
aspx_payload = '''<%@ Page Language="C#" %>
<!--
Migr8 Test ASPX Payload
Harmless reconnaissance payload for upload testing
-->
<!DOCTYPE html>
<html>
<head>
    <title>ASPX Upload Test</title>
</head>
<body>
    <h2>ASPX Upload Test Successful</h2>
    
    <script runat="server">
        void Page_Load(object sender, EventArgs e)
        {
            lblServerInfo.Text = Request.ServerVariables["SERVER_SOFTWARE"];
            lblFramework.Text = Environment.Version.ToString();
            lblCurrentTime.Text = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            lblDirectory.Text = Server.MapPath(".");
            lblOS.Text = Environment.OSVersion.ToString();
        }
    </script>
    
    <p>Server: <asp:Label ID="lblServerInfo" runat="server" /></p>
    <p>.NET Framework: <asp:Label ID="lblFramework" runat="server" /></p>
    <p>Current Time: <asp:Label ID="lblCurrentTime" runat="server" /></p>
    <p>Upload Directory: <asp:Label ID="lblDirectory" runat="server" /></p>
    <p>Operating System: <asp:Label ID="lblOS" runat="server" /></p>
    
    <!-- Migr8 ASPX Test Payload -->
</body>
</html>
'''

with open("migr8/payloads/test.aspx", 'w') as f:
    f.write(aspx_payload)
print("Created: migr8/payloads/test.aspx")

# Create sample.txt payload
txt_payload = '''Migr8 Framework - Sample Text Upload
=====================================

This is a harmless text file used for upload testing.

Upload Details:
- Framework: Migr8 Upload Vulnerability Reconnaissance Tool
- Purpose: File upload functionality testing
- Risk Level: None (harmless test file)

If you can read this file, the upload was successful.

Generated by Migr8 Framework
'''

with open("migr8/payloads/sample.txt", 'w') as f:
    f.write(txt_payload)
print("Created: migr8/payloads/sample.txt")